export const INTERVIEW_QUESTIONS = [
  "How do you approach the integration of personalized nutrition in clinical practice? What factors influence your decision-making in customizing a patient's nutrition plan?",
  "Explain the concept of nutrigenomics and how it might influence personalized dietary recommendations.",
  "Can you describe the role of epigenetics in the development of chronic diseases, and how nutrition might modulate this?",
  "How would you assess the nutritional status of a patient with a complex medical history, such as multiple chronic conditions or cancer?",
  "Discuss the potential impact of the microbiome on nutrition therapy and how you would incorporate microbiome analysis into clinical practice.",
  "What are the primary challenges you face when working with patients who have malnutrition or undernutrition, and how do you overcome them?",
  "How do you approach nutritional interventions for critically ill patients in the ICU, particularly those with severe metabolic imbalances?",
  "What is your approach to managing electrolyte imbalances in hospitalized patients and how does nutrition play a role in correction?",
  "Describe the role of a nutritionist in the multidisciplinary care of patients with eating disorders. How do you balance therapeutic approaches with maintaining patient trust?",
  "How would you manage a patient who is non-compliant with dietary recommendations, particularly when dealing with chronic conditions like diabetes or obesity?",
  "Can you describe a clinical research study you’ve conducted related to nutrition, and what was the outcome?",
  "How do you critically appraise the quality of clinical nutrition research? What criteria do you use to determine the validity and applicability of studies?",
  "What are the key challenges in translating nutrition research into clinical practice, and how can these barriers be overcome?",
  "How do you stay updated with the latest research and advancements in clinical nutrition, and how do you ensure you are using evidence-based practices in your work?",
  "How do you approach a situation where clinical nutrition research is conflicting, and how do you decide which information to implement in patient care?",
  "How would you assess the validity of dietary supplements and functional foods in managing chronic diseases, and what evidence would you rely on to guide your recommendations?",
  "Describe a situation where you used your research to influence a clinical guideline or practice change in a healthcare setting.",
  "How do you approach nutrition interventions in patients with advanced liver disease or renal failure, considering both their metabolic needs and potential restrictions?",
  "Can you describe your strategy for managing nutritional therapy in patients undergoing cancer treatments like chemotherapy or radiation therapy?",
  "What role does nutrition play in managing inflammatory bowel diseases (IBD), and how would you design an individualized diet for a patient with Crohn's disease or ulcerative colitis?",
  "How would you manage the nutritional needs of a patient recovering from bariatric surgery, especially considering the potential for nutrient malabsorption?",
  "How do you assess the effectiveness of a ketogenic diet in patients with epilepsy, cancer, or neurodegenerative diseases, and what are the long-term considerations?",
  "In patients with metabolic syndrome, what nutritional interventions do you prioritize, and how do you monitor the effectiveness of these interventions over time?",
  "How would you utilize technology and digital tools (such as apps or continuous glucose monitoring) to enhance patient care and dietary compliance?",
  "Explain the role of artificial intelligence (AI) in clinical nutrition and how it could impact patient care and personalized nutrition plans.",
  "What is your experience with advanced biochemical techniques (such as metabolomics, proteomics, or genetic testing) in assessing nutrition status, and how would you incorporate these into patient care?",
  "As a clinical nutritionist, how do you approach the ethical considerations when a patient’s dietary needs conflict with cultural, religious, or personal beliefs?",
  "Discuss the ethical dilemmas that might arise in the promotion of dietary supplements or functional foods. How do you navigate these issues while ensuring patient safety?",
  "How do you manage the pressure to recommend trendy diets (e.g., plant-based, gluten-free, ketogenic) when the evidence for their benefits is not conclusive?",
  "Can you explain how you would address a situation where a patient requests a highly restrictive diet that you believe may be harmful to their health?"
]

