export const INTERVIEW_QUESTIONS = [
  "Introduce yourself",
  "Describe a complex case where you integrated personalized nutrition into clinical care. How did you balance genetic data, biochemical markers, comorbidities, medications, and patient lifestyle when formulating the nutrition plan?",
  "Explain how nutrigenomics and nutrigenetics differ, and describe a real-world scenario where genetic polymorphisms directly altered your dietary recommendations.",
  "Discuss the role of epigenetic mechanisms such as DNA methylation and histone modification in chronic disease progression. How can targeted nutritional interventions influence these pathways clinically?",
  "How do you conduct a comprehensive nutritional assessment in patients with multiple chronic illnesses or active malignancy? Which assessment tools, biomarkers, and functional measures do you prioritize, and why?",
  "Critically evaluate the clinical relevance of gut microbiome profiling. How do you distinguish actionable findings from non-clinically significant data when designing nutrition therapy?",
  "Describe your approach to diagnosing and managing protein-energy malnutrition in hospitalized patients. How do you prevent and manage refeeding syndrome in high-risk individuals?",
  "In critically ill ICU patients with sepsis or multi-organ failure, how do you determine enteral versus parenteral nutrition, and how do you adjust macronutrient delivery during different phases of critical illness?",
  "Explain the pathophysiology of electrolyte imbalances such as hyponatremia, hypophosphatemia, and hyperkalemia. How does nutrition therapy contribute to both prevention and correction in hospitalized patients?",
  "Describe your role within a multidisciplinary team managing eating disorders. How do you integrate medical nutrition therapy with psychological treatment while maintaining patient engagement and trust?",
  "How do you manage chronic disease patients who are persistently non-adherent to nutrition recommendations? Describe a case where behavioral strategies significantly improved clinical outcomes.",
  "Describe a clinical or translational nutrition research project you were involved in. What methodology did you use, what were the limitations, and how did the findings influence clinical practice?"
  "When critically appraising clinical nutrition research, how do you assess study design, bias, confounding variables, and clinical relevance before applying findings to patient care?",
  "What are the biggest barriers in translating nutrition research into real-world clinical practice, and how have you personally addressed these challenges in your work?",
  "How do you stay current with emerging evidence in clinical nutrition, and how do you differentiate high-quality evidence from low-quality or industry-biased research?",
  "When faced with conflicting nutrition research (e.g., saturated fat, carbohydrates, or artificial sweeteners), how do you decide what guidance to provide to patients?",
  "How do you evaluate the safety, efficacy, and regulatory status of dietary supplements and functional foods before recommending them for chronic disease management?",
  "Describe a situation where your nutrition research or clinical expertise contributed to a change in hospital policy, protocol, or clinical guideline.",
  "How do you design nutrition therapy for patients with advanced liver disease or end-stage renal disease while balancing metabolic demands, fluid restrictions, and micronutrient risks?",
  "Explain your approach to nutritional management in oncology patients undergoing chemotherapy or radiation. How do you address cachexia, sarcopenia, and treatment-related side effects?",
  "Discuss evidence-based nutrition strategies for inflammatory bowel disease. How do you individualize diets for Crohn’s disease versus ulcerative colitis during active flare and remission?",
  "How do you manage long-term nutritional care after bariatric surgery, including prevention, monitoring, and treatment of micronutrient deficiencies and metabolic complications?",
  "Critically assess the therapeutic use of ketogenic diets in epilepsy, oncology, or neurodegenerative diseases. What are the metabolic risks and long-term clinical considerations?",
  "In patients with metabolic syndrome, which nutrition interventions provide the strongest evidence for improving insulin resistance and cardiovascular risk, and how do you track outcomes over time?",
  "How have you used digital health tools such as continuous glucose monitoring, nutrition tracking apps, or telehealth platforms to improve dietary adherence and clinical outcomes?",
  "Explain how artificial intelligence and machine learning could transform clinical nutrition practice. What are the limitations and ethical concerns associated with AI-driven nutrition planning?",
  "Describe your experience with advanced biochemical assessments such as metabolomics, proteomics, or genetic testing. How do you integrate these data responsibly into clinical decision-making?",
  "How do you address ethical challenges when evidence-based nutrition recommendations conflict with a patient’s cultural, religious, or personal beliefs?",
  "Discuss ethical dilemmas related to the promotion of supplements or functional foods, particularly in vulnerable populations. How do you ensure patient safety and informed consent?",
  "How do you respond to pressure from patients or organizations to promote popular or restrictive diets when robust clinical evidence is lacking?",
  "Describe how you would manage a patient requesting an extremely restrictive diet that poses significant health risks. How do you communicate risk while maintaining a therapeutic relationship?"
];

